### ISSUE TITLE
Gnomes, Gardening, Miscellaneous and Clearance Need Links to pages

### ISSUE THREAD

**Issue by JTY009** [RytisJ/qa_play_project#104]
Presuming a filter method has to be implemented e.g. if customer selects Gnomes then catalogue shows only gnomes

**Comment by Smudgey** [comment]
cc @thelemens

**Comment by thelemens** [comment]
My next challenge is to fill the navbar sections with products matching the correct category.

**Comment by thelemens** [comment]
implemented in #179
