### ISSUE TITLE
Current Gnome product placeholder is inappropriate

### ISSUE THREAD

**Issue by Smudgey** [RytisJ/qa_play_project#130]
Currently the placeholder image for gnome products is a gnome holding open their robe and showing their boxers off. This is inappropriate and kind of needs to be changed.

**Comment by Smudgey** [comment]
@hiketra @HarrisonBaxter

**Comment by HarrisonBaxter** [comment]
I have replaced these images and they are now on a branch that Mark is working on to make them view able along with other pictures for the same product. I also removed and replaced any inappropriate items with more appropriate ones.

**Comment by JTY009** [comment]
Apologise I only changed the link in grid. @thelemens  please pull latest change to over write mine.

**Comment by Smudgey** [comment]
The branch @JTY009 is referencing is #133

**Comment by thelemens** [comment]
All items now have at least one image assigned via a URL.  These are now used in place of any placeholder images that may or may not have been appropriate.  A new issue has been created regarding the size and style of these images

**Comment by Smudgey** [comment]
Referenced issue is #140
