### ISSUE TITLE
'Forgot password?' link in Login Dropdown does nothing

### ISSUE THREAD

**Issue by Smudgey** [RytisJ/qa_play_project#136]
Currently the red link 'Forgot password?' on the Login drop down menu does not have any functionality.

![image](https://cloud.githubusercontent.com/assets/7337624/16990795/4920d21a-4e91-11e6-8d46-0d4b29009645.png)

**Comment by RytisJ** [comment]
Still needs a page to redirect to and backend

**Comment by Smudgey** [comment]
Are we going to support a full pw/email recovery system? Not sure how that would work for us. For now I can redirect to the enquiry page, to imply that they should send an enquiry to the company.

**Comment by Smudgey** [comment]
Fixed in #156
