### ISSUE TITLE
Currently, the basket counter icon and basket itself are out of sync

### ISSUE THREAD

**Issue by Smudgey** [RytisJ/qa_play_project#154]
After navigating back to the basket, the basket data had been wiped but the counter in the basket icon still said 3. 

![image](https://cloud.githubusercontent.com/assets/7337624/17051240/8409f65e-4fef-11e6-8f32-2e5143074e90.png)

**Comment by Smudgey** [comment]
cc @RytisJ @thelemens

**Comment by Smudgey** [comment]
Maybe to be safe, there should be a check between the session and the current basket data? This way they should never go out of sync (session checks current number of objects in basket data array, or however the data is stored, and grabs the value from there.) If the basket is wiped then the counter would return to zero.

**Comment by Smudgey** [comment]
This also happens after an order is completed, as mentioned in #162

**Comment by Smudgey** [comment]
Awaiting a fix from @thelemens

**Comment by thelemens** [comment]
Still waiting for fix from @RytisJ
