### ISSUE TITLE
Review Order Page

### ISSUE THREAD

**Issue by JTY009** [RytisJ/qa_play_project#161]
I suggest adding this page to review the payment of the order that has been confirmed and the items listed in that order.

**Comment by Smudgey** [comment]
Duplicate of #121

**Comment by Smudgey** [comment]
This is actually for customer satisfaction and not for product rating

**Comment by Smudgey** [comment]
Where do we want customer satisfaction to go and what sort of information are we seeking?

**Comment by RytisJ** [comment]
sorted in #184
