### ISSUE TITLE
head imports

### ISSUE THREAD

**Issue by RytisJ** [RytisJ/qa_play_project#2]
<link rel="stylesheet" href="@routes.Assets.versioned("stylesheets/bootstrap.min.css")">
        <link rel="stylesheet" href="@routes.Assets.versioned("stylesheets/bootstrap-theme.css")">
        <script src="@routes.Assets.versioned("javascripts/jquery-3.0.0.min.js")"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

**Comment by Smudgey** [comment]
This is the head import for bootstrap, click edit on the top comment to view the html
