### ISSUE TITLE
Anyone logged in can edit any other users details

### ISSUE THREAD

**Issue by HarrisonBaxter** [RytisJ/qa_play_project#45]
Users can edit other peoples details as long as they're logged in by entering their email address.

**Comment by HarrisonBaxter** [comment]
I think this is an easier problem to fix with the implementation of a database using where maybe?

**Comment by Smudgey** [comment]
Should just get the current user profile, using account id and update those details only, rather than searching for the email address the user entered which anyone could use

**Comment by HarrisonBaxter** [comment]
This has now been fixed
