### ISSUE TITLE
Fix layout of checkout page, add pay now, pay later buttons

### ISSUE THREAD

**Issue by shrek911** [RytisJ/qa_play_project#60]

**Comment by Smudgey** [comment]
Pay now - redirect to a page to select which card a user wishes to use
Pay later - redirect to order confirmation

**Comment by thelemens** [comment]
I still need to create a link to a subsequent payment screen for this, but checkout page now has the option to pay now or later, and creates an order.

**Comment by HarrisonBaxter** [comment]
This has now been fixed
