### ISSUE TITLE
Add an expiration timer to logged in user

### ISSUE THREAD

**Issue by Smudgey** [RytisJ/qa_play_project#84]
At the moment there is no expiration for the session cookie. Add time out.

**Comment by Smudgey** [comment]
cc @shrek911 

how long do you reckon?

**Comment by shrek911** [comment]
15 minutes?

**Comment by HarrisonBaxter** [comment]
A day you stay signed into amazon and other sites for wayyyyyy longer

**Comment by Smudgey** [comment]
After discussion, it was decided that this issue should be abandoned for now. It is a large amount of work that can affect a significant portion of the project for such little functionality.
